# Generated by Django 3.1.13 on 2025-02-12 08:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionLogs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(blank=True, max_length=55, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['id', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('player_id', models.IntegerField(default=None)),
                ('price', models.IntegerField(default=0)),
                ('captain', models.BooleanField(default=False)),
                ('profile', models.CharField(blank=True, max_length=1056, null=True)),
                ('is_unsold', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2025, 2, 12, 14, 19, 9, 90032))),
                ('category', models.CharField(blank=True, max_length=1056, null=True)),
            ],
            options={
                'db_table': 'player',
                'ordering': ['id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('budget', models.IntegerField(default=900000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('max_players', models.IntegerField(default=12)),
            ],
            options={
                'db_table': 'team',
                'ordering': ['id', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['name'], name='team_name_53aa8f_idx'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.team'),
        ),
        migrations.AddField(
            model_name='auctionlogs',
            name='player_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.player'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['name'], name='player_name_342607_idx'),
        ),
    ]
