# Generated by Django 3.1.13 on 2024-09-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_add_team_and_players_sql_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='profile',
            field=models.CharField(blank=True, max_length=1056, null=True),
        ),
    ]
