# Generated by Django 3.1.13 on 2024-09-16 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_player_player_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionLogs',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('player_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.player')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['id', 'created_at'],
            },
        ),
    ]
