# Generated by Django 3.1.13 on 2024-09-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auctionlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlogs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
