# Generated by Django 3.1.13 on 2024-09-16 18:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20240916_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlogs',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
