# Generated by Django 3.1.13 on 2024-09-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20240919_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlogs',
            name='action',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
