# Generated by Django 3.1.13 on 2024-09-19 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auctionlogs_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 19, 21, 24, 34, 55326)),
        ),
    ]
